//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.19.0.0 (NJsonSchema v10.9.0.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming



export interface BannersRequestDto {
    page?: number;
    recordsPerPage?: number;
    positionId: number;
    orderingField?: string | undefined;
    ascendingOrder?: boolean;
}

export interface BannersResponseDto {
    bannerId?: number;
    imageName?: string | undefined;
    imageUrl?: string | undefined;
    linkUrl?: string | undefined;
    priority?: number | undefined;
    positionId?: number | undefined;
    isPublish?: boolean | undefined;
    remark?: string | undefined;
}

export interface BannersResponseDtoListServiceResponse {
    data?: BannersResponseDto[] | undefined;
    isSuccess?: boolean;
    message?: string | undefined;
    code?: number | undefined;
    exceptionMessage?: any | undefined;
    serverDateTime?: Date;
    totalAmountRecords?: number | undefined;
    totalAmountPages?: number | undefined;
    currentPage?: number | undefined;
    recordsPerPage?: number | undefined;
    pageIndex?: number | undefined;
}

export interface PositionsRequestDto {
    page?: number;
    recordsPerPage?: number;
    positionId?: number | undefined;
    positionName?: string | undefined;
    orderingField?: string | undefined;
    ascendingOrder?: boolean;
}

export interface PositionsResponseDto {
    positionId?: number;
    positionName?: string | undefined;
    description?: string | undefined;
    width?: number;
    height?: number;
}

export interface PositionsResponseDtoListServiceResponse {
    data?: PositionsResponseDto[] | undefined;
    isSuccess?: boolean;
    message?: string | undefined;
    code?: number | undefined;
    exceptionMessage?: any | undefined;
    serverDateTime?: Date;
    totalAmountRecords?: number | undefined;
    totalAmountPages?: number | undefined;
    currentPage?: number | undefined;
    recordsPerPage?: number | undefined;
    pageIndex?: number | undefined;
}

export interface StringServiceResponse {
    data?: string | undefined;
    isSuccess?: boolean;
    message?: string | undefined;
    code?: number | undefined;
    exceptionMessage?: any | undefined;
    serverDateTime?: Date;
    totalAmountRecords?: number | undefined;
    totalAmountPages?: number | undefined;
    currentPage?: number | undefined;
    recordsPerPage?: number | undefined;
    pageIndex?: number | undefined;
}

export interface UpsertPositionRequestDto {
    positionId?: number;
    positionName: string;
    description?: string | undefined;
    width?: number;
    height?: number;
}

export interface FileParameter {
    data: any;
    fileName: string;
}